replace tracing info with debug messages
lambdaclass/ethrex pull request #1174
Opened 2024-11-14 17:13 UTC by h3lio5

**Motivation**

Replace `info!` tracing logs with `debug!` to avoid flooding the console.

Closes #1134

2024-11-14 17:17 UTC, h3lio5 commented
From the issue description, I understand that the `debug!` log content should also be made clearer (or less verbose). But this PR doesn't make changes to the log messages though.

2024-11-20 15:08 UTC, ElFantasma commented on crates/networking/p2p/net.rs
> +    debug!("Listening for requests at {tcp_addr}");
I'd rather leave these two lines as `info!` as they appear only once per run in the console.

2024-11-20 15:09 UTC, ElFantasma requested changes
This looks good, but it's a bit outdated: there are some changes in main that should be addressed

2024-11-27 19:31 UTC, ElFantasma approved these changes

2024-11-27 20:41 UTC, merged